name: Indigenous Physicians Association of Canada
favicon: null
layout_spectrum: 0.88397
typography_spectrum: 0.49641
title: Indigenous Physicians Association of Canada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e5826'
    - '#ffffff'
    - '#00b0bf'
    - '#bcad86'
    - '#00757f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
