name: Indigenous Physicians Association of Canada
favicon: null
layout_spectrum: 0.8799758201930672
typography_spectrum: 0.07851365651004016
title: Indigenous Physicians Association of Canada
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6e5826'
    - '#000000'
    - '#00b0bf'
    - '#ba131a'
  brandStrength: 0.75
  lightness: 0.8460662709549069
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
